### PR TITLE
GitHub Action to lint Python code with codespell and ruff

### PR DESCRIPTION
**Pull request by cclauss**
* https://github.com/codespell-project/codespell#readme
* https://beta.ruff.rs/

### CODE REVIEW

**Comment by cclauss** [comment]
Test results: https://github.com/cclauss/remarshal/actions

**Comment by dbohdan** [comment]
Merged in 589594cf49474adfb002cbdfd4a561ea45f300cc. Thanks for the PR; I've been meaning to start using Ruff, and your PR prompted me to. I am not sure I will maintain this pipeline, but I think I will keep using Ruff. IMO jobs like this should run on all branches (consider a PR against a feature branch, for example), so I have changed that.

Some feedback. I recommend defaulting to ["50/72 formatting"](https://stackoverflow.com/questions/2290016/git-commit-messages-50-72-formatting) in GitHub PRs and Git commits in general.  When you work with repos that use a variant of the [Angular commit message format](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#-commit-message-guidelines) (like this one) or the [Conventional Commits](https://www.conventionalcommits.org/en/) spec, it saves maintainers time if you also use it.

**Comment by cclauss** [comment]
I would highly recommend setting up both https://pre-commit.com and https://pre-commit.ci as they save a ton of time.

I contribute to way too many repos that have widely varying commit formats and rebase rules to find a universal standard.

**Comment by cclauss** [comment]
I usually add a commit message like this to explain why I set up the GitHub Action this way...

[Ruff](https://beta.ruff.rs/) supports [over 500 lint rules](https://beta.ruff.rs/docs/rules) and can be used to replace [Flake8](https://pypi.org/project/flake8/) (plus dozens of plugins), [isort](https://pypi.org/project/isort/), [pydocstyle](https://pypi.org/project/pydocstyle/), [yesqa](https://github.com/asottile/yesqa), [eradicate](https://pypi.org/project/eradicate/), [pyupgrade](https://pypi.org/project/pyupgrade/), and [autoflake](https://pypi.org/project/autoflake/), all while executing (in Rust) tens or hundreds of times faster than any individual tool.

The ruff Action uses minimal steps to run in ~5 seconds, rapidly providing intuitive GitHub Annotations to contributors.

image

**Comment by dbohdan** [comment]
> I would highly recommend setting up both https://pre-commit.com/ and https://pre-commit.ci/ as they save a ton of time.

Thanks for the suggestion. I'll check them out.

> I contribute to way too many repos that have widely varying commit formats and rebase rules to find a universal standard.

While I don't have statistics to back this up, I am convinced that more than half the projects with some degree of exposure (for example, repositories with over 100 stars) follow the 50/72 rule. Adopting the format seems like pure gain and no loss to me. Just about nobody will complain about an under-50-character the first line of the commit message being too _short_. It amounts to [being conservative in what you send](https://en.wikipedia.org/wiki/Robustness_principle).

I can't insist you do your work a certain way, of course, but I thought I'd offer my best argument for the 50/72 format.

**Pull request closed without merging**
